# Generated by Django 2.1.5 on 2019-03-06 17:37

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0004_auto_20190306_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.TimeField(default=datetime.datetime(2019, 3, 6, 17, 37, 42, 517528, tzinfo=utc)),
        ),
    ]
