# Generated by Django 2.1.5 on 2019-03-07 18:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0008_auto_20190307_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.TimeField(default=datetime.datetime(2019, 3, 7, 18, 2, 50, 195217, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.TimeField(default=datetime.datetime(2019, 3, 7, 18, 2, 50, 194220, tzinfo=utc)),
        ),
    ]
